title: Foxxxnews
modelClass: foxxxhunt\Foxxxnews\Models\NewsItems
list: $/foxxxhunt/foxxxnews/models/newsitems/columns.yaml
recordUrl: 'foxxxhunt/foxxxnews/foxxxnews/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
